a = int(input("Enter A : "))
b = eval (input("Enter B : "))
print("A + B : ",a+b)
print("A - B : ",a-b)
print("A * B : ",a*b)
print("A / B : ",a/b)
print("A % B : ",a%b)
print("A ** B : ",a**b)
print("A // B : ",a//b)